[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.prediction"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10